=== mah-luke/semistructured-data/exercises/exercise2/working/template/resources/vaccination-plan.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <xsd:element name="vaccination-plan" type="vaccinationPlanType">
    <xsd:key name="vaccineTypeKey">
      <xsd:selector xpath="vaccine-types/vaccine"/>
      <xsd:field xpath="name"/>
    </xsd:key>
    <xsd:key name="batchKey">
      <xsd:selector xpath="vaccines/vaccine/batch"/>
      <xsd:field xpath="@id"/>
    </xsd:key>
    <xsd:key name="patientKeys">
      <xsd:selector xpath="patients/patient"/>
      <xsd:field xpath="@pid"/>
    </xsd:key>
    <xsd:keyref name="vaccineTypeRef" refer="vaccineTypeKey">
      <xsd:selector xpath="./vaccines/vaccine"/>
      <xsd:field xpath="@type_ref"/>
    </xsd:keyref>
    <xsd:keyref name="batchRef" refer="batchKey">
      <xsd:selector xpath="./patients/patient/vaccine"/>
      <xsd:field xpath="@ref_batch"/>
    </xsd:keyref>
  </xsd:element>
  
  <xsd:complexType name="vaccinationPlanType">
    <xsd:all>
      <xsd:element name="vaccine-types" type="vaccineTypesType" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="vaccines" type="vaccinesType" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="patients" type="patientsType" minOccurs="1" maxOccurs="1"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="vaccineTypesType">
    <xsd:sequence>
      <xsd:element name="vaccine" type="vaccineType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="vaccineType">
    <xsd:all>
      <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
	  <xsd:element name="authorized" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
	  <xsd:element name="type" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    </xsd:all>
  </xsd:complexType>
  
  <xsd:complexType name="vaccinesType">
    <xsd:sequence>
      <xsd:element name="vaccine" type="vaccineBatchType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>


  <xsd:complexType name="vaccineBatchType">
	  <xsd:sequence minOccurs="1" maxOccurs="unbounded">
	    <xsd:element name="batch" type="batchType" minOccurs="1" maxOccurs="1"/>
	    <xsd:element name="info" type="infoType" minOccurs="0" maxOccurs="1"/>
	  </xsd:sequence>
      <xsd:attribute name="type_ref" type="xsd:string" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="batchType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
		<xsd:attribute name="id" type="batchIdType" use="required"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="batchIdType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Z][a-z]{2}[A-Z]-[0-9]{4}-[0-9][A-Z][0-9]"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="infoType" mixed="true">
    <xsd:sequence>
      <xsd:element name="size" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
	  <xsd:element name="order-date" type="xsd:date" minOccurs="1" maxOccurs="1"/>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
	    <xsd:element name="size" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
	    <xsd:element name="delivery-date" type="xsd:date" minOccurs="1" maxOccurs="3"/>
      </xsd:sequence>
    </xsd:sequence>
	<xsd:attribute name="date" type="xsd:date" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="patientsType">
    <xsd:sequence>
      <xsd:element name="patient" type="patientType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="patientType">
	<xsd:sequence>
	  <xsd:element name="risk-group" type="riskGroupType" minOccurs="1" maxOccurs="1"/>
	  <xsd:sequence minOccurs = "0" maxOccurs = "2">
	    <xsd:element name="vaccine" type="vaccinePType" minOccurs="1" maxOccurs="1"/>
	    <xsd:element name="vaccination-date" type="vaccinationDateType" minOccurs="1" maxOccurs="1"/>
	  </xsd:sequence>
	  <xsd:element name="residences" type="residencesType" minOccurs="1" maxOccurs="1">
	    <xsd:unique name="residencePlaces">
		  <xsd:selector xpath="./second | ./main"/>
          <xsd:field xpath="."/>
        </xsd:unique>
	  </xsd:element>
	</xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>  
	<xsd:attribute name="birth_year" type="xsd:int"/>  
	<xsd:attribute name="pid" type="pidIdType" use="required"/>
  </xsd:complexType>
  
  <xsd:simpleType name="pidIdType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="P[0-9]+"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="riskGroupType">
    <xsd:restriction base="xsd:string">
	  <xsd:enumeration value="High"/>
	  <xsd:enumeration value="Medium"/>
	  <xsd:enumeration value="Low"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:complexType name="vaccinePType">
	<xsd:attribute name="ref_batch" type="batchIdType" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="vaccinationDateType">
    <xsd:attribute name="date" type="xsd:date" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="residencesType">
	<xsd:sequence>
	  <xsd:element name="second" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
	  <xsd:element name="main" type="xsd:string" minOccurs="1" maxOccurs="1"/>
	  <xsd:element name="second" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
  </xsd:complexType>
  
</xsd:schema>

=== mah-luke/semistructured-data/exercises/exercise2/working/template/resources/vaccination-plan-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<vaccination-plan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../resources/vaccination-plan.xsd">
	<vaccine-types>
		<vaccine> 
			<name>Pfizer/BioNTech</name>
			<authorized>true</authorized>
			<type>mRNA</type>
		</vaccine>
		<vaccine> 
			<name>Moderna</name>
			<authorized>true</authorized>
			<type>mRNA</type>
		</vaccine>
		<vaccine> 
			<name>AstraZeneca</name>
			<type>Adenovirus-based</type>
			<authorized>true</authorized>
		</vaccine>
		<vaccine> 
			<authorized>false</authorized>
			<name>Sputnik V</name>
			<type>Adenovirus-based</type>
		</vaccine>
	</vaccine-types>

	<vaccines>
		<vaccine type_ref = "AstraZeneca">
			<batch id = "AstZ-5587-8B5">
				First batch
			</batch>
			<info date="2021-01-01">
				<size>5000</size> doses will be ordered on <order-date>2021-04-01</order-date>.
			</info>
			<batch id = "AstZ-8872-3C4">
				Second batch
			</batch>
			<info date="2021-03-13">
				<size>15000</size> have been ordered on <order-date>2021-03-10</order-date>.
			</info>
		</vaccine>
		<vaccine type_ref = "Pfizer/BioNTech">
			<batch id = "BioN-1255-7A7">
				Adapted batch for B.1.1.7
			</batch>
			<info date="2021-01-10">
				An order for a total size of <size>16000</size> doses has been placed on <order-date>2021-01-10</order-date>.
				<size>5500</size> doses will arrive on <delivery-date>2021-02-01</delivery-date>.
				Additionally, <size>10500</size> doses will arrive on <delivery-date>2021-02-20</delivery-date> and <delivery-date>2021-02-21</delivery-date>.
			</info>
			<batch id = "BioN-2726-2D9">
				Adapted batch for B.1.1.8
			</batch>
		</vaccine>
		<vaccine type_ref = "Moderna">
			<batch id = "ModE-1351-3B6">
				Adapted batch for B.1.351
			</batch>
			<batch id = "ModE-1125-2C8">
				Adapted batch for B.1.1.7
			</batch>
			<info date="2021-04-29">
				An order for a total size of <size>10000</size> doses will be placed on <order-date>2021-05-10</order-date>.
			</info>
		</vaccine>
	</vaccines>
	
	<patients>
		<patient name = "Elisabeth Drosten" birth_year = "1940" pid = "P150">
			<risk-group>High</risk-group>
			<vaccine ref_batch = "BioN-1255-7A7"/>
			<vaccination-date date = "2021-02-05"/>
			<vaccine ref_batch = "BioN-2726-2D9"/>
			<vaccination-date date = "2021-03-01"/>
			<residences>
				<second>
					Burgenland, AT
				</second>
				<main>
					Vienna, AT
				</main>
				<second>
					Lingen, DE
				</second>
				<second>
					Downey, US
				</second>
				<second>
					Woolsthorpe Manor, UK
				</second>
			</residences>
		</patient>
		<patient name = "Lydia Bernoulli" birth_year = "1972" pid = "P27780">
			<risk-group>Medium</risk-group>
			<vaccine ref_batch = "AstZ-8872-3C4"/>
			<vaccination-date date = "2021-05-15"/>
			<residences>
				<second>
					Basel, CH
				</second>
				<main>
					Vienna, AT
				</main>
			</residences>
		</patient>
		<patient name = "Victoria Sealy Gosset" pid = "P152847">
			<risk-group>Low</risk-group>
			<vaccine ref_batch = "AstZ-8872-3C4"/>
			<vaccination-date date = "2021-06-30"/>
			<residences>
				<main>
					Vienna, AT
				</main>
			</residences>
		</patient>
	</patients>
</vaccination-plan>
